# Generated by Django 4.1.1 on 2022-09-26 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User_signup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_fname', models.TextField(max_length=20)),
                ('user_lname', models.TextField(max_length=20)),
                ('user_email', models.EmailField(max_length=254)),
                ('user_contact', models.IntegerField()),
                ('user_cnic', models.IntegerField()),
                ('user_address', models.TextField(blank=True, max_length=255, null=True)),
                ('user_password', models.CharField(max_length=8)),
                ('user_conf_password', models.CharField(max_length=8)),
            ],
        ),
    ]
